# Generated by Django 5.2.1 on 2025-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_previous_password_hash1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
